### ISSUE TITLE
По-моему, очепятка)

### ISSUE THREAD

**Issue by paramaribo35** [hexlet-basics/hexlet_basics#112]
В 9-ом уроке по HTML есть пример списка "Сходить в Алексею". Наверное подразумевалось "Сходить К Алексею"? 
Потом в 18 уроке ещё опечатка. Написано "Используйте слудеющие аудио файлы". 
В 20-м уроке есть текст "Простейщая разметка".

**Comment by Graph1589** [comment]
В данный момент первые две опечатки исправлены. Третья исправлена в исходниках, но на сайте отображается по-старому - "простейщая".

**Comment by amshkv** [comment]
Эти ошибки на сайте уже исправлены, спасибо!)
