### ISSUE TITLE
По-моему, очепятка) V 1.1

### ISSUE THREAD

**Issue by Dreamscat4er** [hexlet-basics/hexlet_basics#148]
Во втором уроке по javascript в примере "You know nothing, Jon Snow!." в имени пропущена h - John.

**Comment by nikolaenkoOleg** [comment]
Неа, гугл говорит, что его имя так и пишется в оригинале.

**Comment by astynax** [comment]
Потому что он не Джон никакой, хоть у нас так и перевели. Смесь "Жана" с "Йоном"

**Comment by Dreamscat4er** [comment]
Вы оригинал читали? Тогда мое уважение) У меня тоже в планах прочитать в
оригинале

вс, 12 янв. 2020 г. в 14:52, Aleksei Pirogov <notifications@github.com>:

**Comment by nikolaenkoOleg** [comment]
Может, тогда закрыть ишью?)
