### ISSUE TITLE
Опечатка в Уроке #42

### ISSUE THREAD

**Issue by ib0ndar** [hexlet-basics/hexlet_basics#154]
> Насколько он разный - не важно, даже если хотя бы один раз из миллиона вызовов вернет что-то другое, эта функция автоматически считается **не детерминированной**.

"**Недетерминированной**" пишется слитно.

**Comment by morphizm** [comment]
Это JS, я взял

**Comment by morphizm** [comment]
и отправил пул реквест туда

**Comment by sergey-nechaev** [comment]
Было исправлено тут - https://github.com/hexlet-basics/exercises-javascript/pull/154, можно закрывать.
