### ISSUE TITLE
Очистка редактора после проверки

### ISSUE THREAD

**Issue by samokisha** [hexlet-basics/hexlet_basics#53]
После нажатия кнопки `Проверить`, редактор очищается.
При неправильном решении задания получаем пустой редактор и приходится писать весь код заново.

Проблема обнаружена в `java → Определение функций 37/59`

**Comment by samokisha** [comment]
Update:
После переключения вкладок `Редактор`, `Консоль`, `Решение`, пропадает содержимое редактора.

**Comment by mokevnin** [comment]
fixed, thanks!
